### ISSUE TITLE
在“博客”页面无法通过点击卡片跳转至对应博客，只能通过点击“阅读全文”来跳转

### ISSUE THREAD

**Issue by Rokixy** [linxiaowu66/doumi-nextjs#1]
现象：点击下图中红框区域，虽然有ripple效果，但并没有跳转至对应页面

![image](https://github.com/linxiaowu66/doumi-nextjs/assets/48944401/b0ea7f8a-3c7b-497b-8270-7f2d4f3bdcf8)

预期：点击红框区域与点击“阅读全文”效果相同，鼠标左键和中键都可以打开博客

**Comment by linxiaowu66** [comment]
已修复哈，感谢提issue

**Comment by linxiaowu66** [comment]
close
