### ISSUE TITLE
样式问题：提交按钮部分区域被覆盖(被右侧标题栏挡住)

### ISSUE THREAD

**Issue by telescope114** [linxiaowu66/doumi-nextjs#2]
浏览器信息： chrome  v123.0.6312.124

![image](https://github.com/linxiaowu66/doumi-nextjs/assets/64593276/d98242bf-f7e1-4a9c-a925-8afc8737a31b)

![image](https://github.com/linxiaowu66/doumi-nextjs/assets/64593276/6f8bf553-7cf0-4c38-9d7e-66aba3a1fd40)

**Comment by linxiaowu66** [comment]
已修改，控制宽度
